// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDCqGO6ShLPLBosMIMluMI6ALCfbXyz8A',
    appId: '1:548945350115:web:8284d55ccd504d7e39a4d6',
    messagingSenderId: '548945350115',
    projectId: 'sneakershoppingapp',
    authDomain: 'sneakershoppingapp.firebaseapp.com',
    storageBucket: 'sneakershoppingapp.appspot.com',
    measurementId: 'G-L4506FVF8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAlrSvr8Bis-xFyqX80nyk7N30h1GuKMc',
    appId: '1:548945350115:android:32d9a9dd7be5256a39a4d6',
    messagingSenderId: '548945350115',
    projectId: 'sneakershoppingapp',
    storageBucket: 'sneakershoppingapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy-_nZWaL3mHsSzZj8Vh6h2vR2kCqi_mA',
    appId: '1:548945350115:ios:b61368a1270b399339a4d6',
    messagingSenderId: '548945350115',
    projectId: 'sneakershoppingapp',
    storageBucket: 'sneakershoppingapp.appspot.com',
    androidClientId: '548945350115-kd1o97nhn6li1q13lkhu6pnqvufvdjg9.apps.googleusercontent.com',
    iosClientId: '548945350115-b9qrh7oijd089ke1geq0j261cduf5ps4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sneakershoppingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy-_nZWaL3mHsSzZj8Vh6h2vR2kCqi_mA',
    appId: '1:548945350115:ios:85127deea95954df39a4d6',
    messagingSenderId: '548945350115',
    projectId: 'sneakershoppingapp',
    storageBucket: 'sneakershoppingapp.appspot.com',
    androidClientId: '548945350115-kd1o97nhn6li1q13lkhu6pnqvufvdjg9.apps.googleusercontent.com',
    iosClientId: '548945350115-inckg586t7er18pcbjh51tt3f89abeup.apps.googleusercontent.com',
    iosBundleId: 'com.example.sneakershoppingapp.RunnerTests',
  );
}
